### ISSUE TITLE
Cannot install...

### ISSUE THREAD

**Issue by petasis** [kaflesudip/grabfeed#10]
Hi all,

pip install grabfeed

fails in python3: 

grabfeed 0.4 has requirement requests==2.8.1, but you'll have requests 2.19.1 which is incompatible.

**Comment by petasis** [comment]
And has problems also with beautifulsoup:

grabfeed 0.4 has requirement beautifulsoup4==4.4.1, but you'll have beautifulsoup4 4.6.3 which is incompatible.
grabfeed 0.4 has requirement requests==2.8.1, but you'll have requests 2.19.1 which is incompatible.

**Comment by kaflesudip** [comment]
You need to install it inside virtualenv.
