### ISSUE TITLE
RSS not found for url, while it has got one indeed

### ISSUE THREAD

**Issue by JohnPlayerSpecial** [kaflesudip/grabfeed#5]
I know it could be something personal, but..
your code doesn't find the feed for the following URL:

`rss_feed = return_rss('http://rischiocalcolato.it')`

it gives

`raise Exception("The page has no RSS feed")`

Feed is indeed present at http://rischiocalcolato.it/feed

I'm bothering you with all these issues because I'm using your code ( thanks!!! <3 ) because I'm (trying) to build a telegram bot RSS reader, cloning the official @TheFeedReaderBot

Thanks

**Comment by kaflesudip** [comment]
THanks @JohnPlayerSpecial. The basic logic for detecting RSS feed is to look into html head for `type='application/atom+xml'` or `type='application/rss+xml'`. The page you specified hasn't specified that in header.
